name: "Delete default VPC"

# Trigger when commits are pushed to the master branch

on:
  push:
    branch:
      - master

env:

  AWS_DEFAULT_REGION: ap-south-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCESS_KEY_ID: ${{ secrets.DELIVER_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DELIVER_AWS_SECRET_ACCESS_KEY }}

jobs:

  build:
    name: Deliver ShellScript
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{env.AWS_DEFAULT_REGION}}
    - name: delete default vpc
      run: sh ./aws-delete-default-vpc.sh
